CAF-3862: Updated to use new opensuse-elasticsearch image
caf-archive/policy-elasticsearch-container pull request #3
Opened 2017-12-13 17:24 UTC by michael-bryson

Dev build: http://sou-jenkins2.hpeswlab.net/job/CAFDataProcessing/view/Developer/job/CAFDataProcessing~policy-elasticsearch-container~CAF-3862~CI/

This has been consumed by policy server in CAF-3862 branch here: https://github.com/CAFDataProcessing/policy-server/tree/CAF-3862
Dev build for this: http://sou-jenkins2.hpeswlab.net/job/CAFDataProcessing/view/Developer/job/CAFDataProcessing~policy-server~CAF-3862~CI/

2017-12-13 19:18 UTC, dermot-hardy approved these changes

2017-12-13 19:22 UTC, dermot-hardy requested changes
This should be a major version update on this container, as it is a breaking change - i.e. consuming this new version requires changes to the caller.

2017-12-14 09:07 UTC, michael-bryson commented
@dermot-hardy No problem re the version change. However I need more detail as to what you mean by "consuming this new version requires changes to the caller" so I can add that to the release notes.

2017-12-14 13:14 UTC, dermot-hardy approved these changes
I should have said "may require changes".  For example, if they were previously using Debian tools like `apt-get` then updates would be required.

2017-12-14 20:29 UTC, merged